package tw.xiaoxin.relens;

import android.Manifest;import android.app.*;import android.content.*;import android.graphics.*;import android.media.MediaScannerConnection;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.provider.Settings;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
import com.google.android.material.bottomnavigation.BottomNavigationView;import com.google.android.material.card.MaterialCardView;

public class MainActivity extends Activity implements ReConnectionManager.Listener,AppLog.Listener {
    private static final int EXPORT_LOG=81,NAV_CONNECTION=100,NAV_CAPTURE=101,NAV_ALBUM=102,NAV_STREAM=103,NAV_DEVICE=104;private final ExecutorService io=Executors.newFixedThreadPool(3);private LinearLayout root,body,statusPanel;private BottomNavigationView nav;private TextView status,console;private EditText host;private ReApi api;private ReConnectionManager connection;private android.content.SharedPreferences prefs;private boolean dark;private int ink,paper,surface,muted,signal;private String sessionCameraPassword="";private YouTubeAuthManager youtubeAuth;private YouTubeLiveClient youtube;private YouTubeLiveClient.Session youtubeSession;private int pageGeneration;
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("settings",MODE_PRIVATE);dark=prefs.getBoolean("dark",false);colors();showShell();requestPermissionsIfNeeded();connection=ReConnectionManager.get(this);connection.addListener(this);AppLog.addListener(this);youtubeAuth=new YouTubeAuthManager(this,new YouTubeAuthManager.Listener(){public void onToken(String token){youtube=new YouTubeLiveClient(token);runOnUiThread(()->{toast("YouTube 已授權");showStream();});}public void onError(String message){runOnUiThread(()->toast("YouTube 授權失敗："+message));}});if(prefs.getBoolean("background",false)){Intent monitor=new Intent(this,ConnectionMonitorService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(monitor);else startService(monitor);}showConnection();AppLog.i("APP","App opened");}
    private void colors(){paper=Color.rgb(dark?20:245,dark?24:245,dark?24:239);surface=Color.rgb(dark?35:229,dark?42:233,dark?41:228);ink=Color.rgb(dark?235:23,dark?239:32,dark?235:31);muted=Color.rgb(dark?180:75,dark?189:82,dark?184:79);signal=Color.rgb(dark?77:0,dark?208:121,dark?190:107);getWindow().setStatusBarColor(paper);getWindow().setNavigationBarColor(paper);getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);}
    private void showShell(){root=column();root.setBackgroundColor(paper);LinearLayout top=column();top.setPadding(dp(20),dp(12),dp(20),dp(8));TextView brand=text("RE LENS",12,true);brand.setLetterSpacing(.16f);brand.setTextColor(signal);top.addView(brand,lp(-1,dp(24)));LinearLayout head=row();status=text("尚未連線",16,true);head.addView(status,new LinearLayout.LayoutParams(0,dp(48),1));host=new EditText(this);host.setSingleLine();host.setText("192.168.49.1");host.setHint("RE IP");host.setTextColor(ink);host.setHintTextColor(muted);host.setContentDescription("HTC RE IP 位址");head.addView(host,new LinearLayout.LayoutParams(dp(144),dp(48)));top.addView(head);root.addView(top);body=column();body.setPadding(dp(20),dp(12),dp(20),dp(28));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));nav=new BottomNavigationView(this);nav.setBackgroundColor(surface);nav.getMenu().add(0,NAV_CONNECTION,0,"連線").setIcon(android.R.drawable.stat_sys_data_bluetooth);nav.getMenu().add(0,NAV_CAPTURE,1,"拍攝").setIcon(android.R.drawable.ic_menu_camera);nav.getMenu().add(0,NAV_ALBUM,2,"相簿").setIcon(android.R.drawable.ic_menu_gallery);nav.getMenu().add(0,NAV_STREAM,3,"串流").setIcon(android.R.drawable.ic_media_play);nav.getMenu().add(0,NAV_DEVICE,4,"裝置").setIcon(android.R.drawable.ic_menu_info_details);nav.setLabelVisibilityMode(BottomNavigationView.LABEL_VISIBILITY_LABELED);nav.setOnItemSelectedListener(item->{if(item.getItemId()==NAV_CONNECTION)showConnection();else if(item.getItemId()==NAV_CAPTURE)showCapture();else if(item.getItemId()==NAV_ALBUM)showAlbum();else if(item.getItemId()==NAV_STREAM)showStream();else showDevice();return true;});root.addView(nav,lp(-1,dp(72)));setContentView(root);}
    private void showConnection(){
        clear("連線總覽","從這裡確認無線功能、RE 與資料鏈路是否就緒。");
        MaterialCardView dashboard=card();statusPanel=cardBody(dashboard);statusPanel.addView(text("連線狀態",17,true));body.addView(dashboard);
        addStatus("手機藍牙",connection.bluetoothOn()?"已開啟":"未開啟");
        addStatus("手機 Wi‑Fi",connection.wifiOn()?"已開啟":"未開啟");
        addStatus("BLE",connection.bleState());
        addStatus("Wi‑Fi Direct",connection.p2pState());
        addStatus("HTTP",connection.httpState());
        addStatus("即時預覽","未來功能");
        section("RE 相機密碼");
        EditText password=new EditText(this);
        password.setSingleLine();
        password.setHint("輸入既有相機密碼");
        password.setText(sessionCameraPassword);
        password.setTextColor(ink);
        password.setHintTextColor(muted);
        password.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);
        password.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(15)});
        password.setContentDescription("HTC RE 相機密碼");
        password.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){sessionCameraPassword=s.toString();connection.setCameraPassword(sessionCameraPassword);}public void afterTextChanged(android.text.Editable s){}});
        body.addView(password,lp(-1,dp(56)));
        TextView privacy=text("密碼只保留在本次 App 執行期間，不會寫入操作 Log。",13,false);
        privacy.setTextColor(muted);
        body.addView(privacy,lp(-1,dp(40)));
        Button verify=button("驗證密碼",false);
        verify.setOnClickListener(v->{if(connection.retryPasswordVerification(password.getText().toString()))toast("已送出密碼驗證");});
        body.addView(verify,lp(-1,dp(52)));
        section("首次設定／硬體重設後");
        TextView setupHint=text("先連線已完成硬體重設的 RE，再設定 8–15 個字元的新密碼。App 會先確認原廠密碼，不會覆寫仍受舊密碼保護的裝置。",13,false);
        setupHint.setTextColor(muted);
        setupHint.setPadding(0,0,0,dp(8));
        body.addView(setupHint);
        EditText newPassword=passwordField("新密碼");
        EditText confirmation=passwordField("再次輸入新密碼");
        body.addView(newPassword,lp(-1,dp(56)));
        body.addView(confirmation,lp(-1,dp(56)));
        Button initialize=button("設定首次使用密碼",false);
        initialize.setOnClickListener(v->{if(connection.beginInitialPasswordSetup(newPassword.getText().toString(),confirmation.getText().toString()))toast("正在確認 RE 原廠狀態");});
        body.addView(initialize,lp(-1,dp(52)));
        LinearLayout a=row();
        Button detect=button("偵測 RE",true);
        detect.setOnClickListener(v->connection.scanBle());
        Button connect=button("連線",false);
        connect.setOnClickListener(v->{connection.setCameraPassword(password.getText().toString());connection.connectFound();});
        a.addView(detect,new LinearLayout.LayoutParams(0,dp(56),1));
        a.addView(connect,new LinearLayout.LayoutParams(0,dp(56),1));
        body.addView(a);
        LinearLayout b=row();
        Button p2p=button("建立 Wi‑Fi Direct",false);
        p2p.setOnClickListener(v->connection.createP2pGroup());
        Button check=button("檢查狀態",false);
        check.setOnClickListener(v->showConnection());
        b.addView(p2p,new LinearLayout.LayoutParams(0,dp(56),1));
        b.addView(check,new LinearLayout.LayoutParams(0,dp(56),1));
        body.addView(b);
        Button disconnect=button("中斷連線",false);
        disconnect.setOnClickListener(v->connection.disconnect());
        body.addView(disconnect,lp(-1,dp(56)));
        section("連線偏好");
        Switch bg=toggle("允許背景連線",prefs.getBoolean("background",false));
        bg.setOnCheckedChangeListener((x,on)->{prefs.edit().putBoolean("background",on).apply();Intent i=new Intent(this,ConnectionMonitorService.class);if(on){if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}else stopService(i);});
        body.addView(bg);
        Switch alert=toggle("斷線時顯示通知",prefs.getBoolean("disconnect_alert",true));
        alert.setOnCheckedChangeListener((x,on)->prefs.edit().putBoolean("disconnect_alert",on).apply());
        body.addView(alert);
        Button wireless=button("開啟無線設定",false);
        wireless.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS)));
        body.addView(wireless,lp(-1,dp(52)));
    }
    private void addStatus(String label,String value){LinearLayout l=row();l.setPadding(0,dp(5),0,dp(5));TextView a=text(label,14,false);a.setTextColor(muted);TextView b=text(value,14,true);b.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);b.setTextColor(value.contains("失敗")||value.contains("未開啟")?Color.rgb(186,26,26):ink);l.addView(a,new LinearLayout.LayoutParams(0,dp(40),1));l.addView(b,new LinearLayout.LayoutParams(0,dp(40),1));(statusPanel==null?body:statusPanel).addView(l);}
    private void showCapture(){clear("拍照 / 攝影","拍攝控制已可使用；即時預覽列為後續功能。");MaterialCardView notice=card();LinearLayout note=cardBody(notice);TextView title=text("即時預覽尚未支援",17,true);note.addView(title);TextView detail=text("RE 使用 RTP/JPEG payload type 26，目前播放器無法解碼。這不影響拍照與錄影控制。",14,false);detail.setTextColor(muted);detail.setPadding(0,dp(8),0,0);note.addView(detail);body.addView(notice,lp(-1,-2));TextView mode=text("相機就緒",15,true);mode.setGravity(Gravity.CENTER);mode.setPadding(0,dp(12),0,dp(8));body.addView(mode,lp(-1,dp(60)));Button shutter=button("拍照",true);shutter.setTextSize(20);shutter.setOnClickListener(v->run("正在拍照…",()->api().capture(),o->mode.setText("照片已拍攝")));body.addView(shutter,lp(-1,dp(64)));LinearLayout rec=row();Button start=button("開始錄影",false),stop=button("停止錄影",false);start.setOnClickListener(v->run("正在開始錄影…",()->api().startRecording(),o->mode.setText("錄影中")));stop.setOnClickListener(v->run("正在停止錄影…",()->api().stopRecording(),o->mode.setText("錄影已儲存")));rec.addView(start,new LinearLayout.LayoutParams(0,dp(60),1));rec.addView(stop,new LinearLayout.LayoutParams(0,dp(60),1));body.addView(rec);}
    private void showAlbum(){clear("RE 相簿","讀取相機媒體清單；下載支援斷點續傳。");Button refresh=button("重新整理",true);refresh.setOnClickListener(v->showAlbum());body.addView(refresh,lp(-1,dp(56)));loadMedia();}
    private void loadMedia(){run("正在讀取相簿…",()->api().media(),a->{status.setText(a.length()+" 個項目");if(a.length()==0){body.addView(text("RE 上目前沒有照片或影片。",15,false));return;}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String id=o.optString("id","item-"+i),name=o.optString("name",id);MaterialCardView itemCard=card();LinearLayout box=cardBody(itemCard);String size=o.optLong("size",0)>0?" · "+formatBytes(o.optLong("size")):"";box.addView(text(name,16,true));TextView meta=text(mediaLabel(o.optString("type","media"))+size,13,false);meta.setTextColor(muted);box.addView(meta);LinearLayout actions=row();Button dl=button("下載",false),del=button("從 RE 刪除",false);dl.setOnClickListener(v->download(id,o));del.setTextColor(Color.rgb(186,26,26));del.setOnClickListener(v->confirmDelete(o,name));actions.addView(dl,new LinearLayout.LayoutParams(0,dp(52),1));actions.addView(del,new LinearLayout.LayoutParams(0,dp(52),1));box.addView(actions);body.addView(itemCard,lp(-1,-2));}});}
    private void download(String id,JSONObject item){final int generation=pageGeneration;String name=item.optString("name",id).replaceAll("[^a-zA-Z0-9._-]","_");status.setText("下載中…");AppLog.i("DOWNLOAD","GC1 MediaStore transfer started handle="+item.optLong("handle"));io.execute(()->{Uri pending=null;try{boolean video=isVideo(item,name);if(Build.VERSION.SDK_INT>=29){ContentValues values=new ContentValues();values.put(MediaStore.MediaColumns.DISPLAY_NAME,name);values.put(MediaStore.MediaColumns.MIME_TYPE,mediaMime(video,name));values.put(MediaStore.MediaColumns.RELATIVE_PATH,(video?Environment.DIRECTORY_MOVIES:Environment.DIRECTORY_PICTURES)+"/RE Lens");values.put(MediaStore.MediaColumns.IS_PENDING,1);Uri collection=video?MediaStore.Video.Media.EXTERNAL_CONTENT_URI:MediaStore.Images.Media.EXTERNAL_CONTENT_URI;pending=getContentResolver().insert(collection,values);if(pending==null)throw new IOException("MediaStore 無法建立目的檔案");try(OutputStream out=getContentResolver().openOutputStream(pending,"w")){if(out==null)throw new IOException("MediaStore 無法開啟目的檔案");api().download(item,out,(d,t)->updateDownloadProgress(generation,d,t));}ContentValues ready=new ContentValues();ready.put(MediaStore.MediaColumns.IS_PENDING,0);getContentResolver().update(pending,ready,null,null);AppLog.i("DOWNLOAD","MediaStore transfer completed uri="+pending);pending=null;}else{File dir=new File(Environment.getExternalStoragePublicDirectory(video?Environment.DIRECTORY_MOVIES:Environment.DIRECTORY_PICTURES),"RE Lens");if(!dir.exists()&&!dir.mkdirs())throw new IOException("無法建立公開媒體目錄");File out=new File(dir,name);api().download(item,out,(d,t)->updateDownloadProgress(generation,d,t));MediaScannerConnection.scanFile(this,new String[]{out.getAbsolutePath()},new String[]{mediaMime(video,name)},null);AppLog.i("DOWNLOAD","Public media transfer completed path="+out.getAbsolutePath());}runOnUiThread(()->{if(generation==pageGeneration)toast("已儲存至系統"+(video?"影片":"相簿")+"：RE Lens/"+name);});}catch(Exception e){if(pending!=null)getContentResolver().delete(pending,null,null);AppLog.e("DOWNLOAD",e);runOnUiThread(()->{if(generation==pageGeneration)error(e);});}});}
    private void updateDownloadProgress(int generation,long done,long total){runOnUiThread(()->{if(generation==pageGeneration)status.setText(total>0?(done*100/total)+"%":"已下載 "+done);});}
    private static boolean isVideo(JSONObject item,String name){String type=item.optString("type","");String lower=name.toLowerCase(java.util.Locale.ROOT);return !"photo".equals(type)&&(type.contains("video")||"timelapse".equals(type)||"slow_motion".equals(type)||lower.endsWith(".mp4")||lower.endsWith(".mov"));}
    private static String mediaMime(boolean video,String name){String lower=name.toLowerCase(java.util.Locale.ROOT);if(video)return lower.endsWith(".mov")?"video/quicktime":"video/mp4";return lower.endsWith(".png")?"image/png":"image/jpeg";}
    private void stopPreview(){}
    private void showStream(){clear("串流","RE 預覽與 YouTube Live 共用這個工作區，但各自維持獨立狀態。");section("RE 即時預覽");body.addView(text("rtsp://"+host.getText().toString().trim()+"/live\nRTSP 解碼器尚待接入 StreamController。",15,false));section("YouTube Live");body.addView(text(youtube==null?"尚未授權 Google 帳戶":"Google 帳戶已授權",15,true));Button auth=button(youtube==null?"連結 YouTube":"重新授權",false);auth.setOnClickListener(v->youtubeAuth.authorize());body.addView(auth,lp(-1,dp(52)));EditText title=new EditText(this);title.setText("HTC RE Live");title.setHint("直播標題");title.setTextColor(ink);title.setHintTextColor(muted);title.setContentDescription("YouTube 直播標題");body.addView(title,lp(-1,dp(56)));Spinner privacy=new Spinner(this);String[] options={"不公開","私人","公開"};privacy.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,options));body.addView(privacy,lp(-1,dp(56)));Button prepare=button("建立 YouTube 直播",true);prepare.setEnabled(youtube!=null);prepare.setOnClickListener(v->{String[] values={"unlisted","private","public"};runYouTube("正在建立 YouTube 直播…",()->youtube.createSession(title.getText().toString().trim(),values[privacy.getSelectedItemPosition()]),s->{youtubeSession=s;showStream();});});body.addView(prepare,lp(-1,dp(56)));if(youtubeSession!=null){body.addView(text("Broadcast 已建立\n觀看網址："+youtubeSession.watchUrl+"\nRTMP："+youtubeSession.maskedIngest(),14,false));Button copy=button("複製觀看網址",false);copy.setOnClickListener(v->{getSystemService(android.content.ClipboardManager.class).setPrimaryClip(android.content.ClipData.newPlainText("YouTube Live",youtubeSession.watchUrl));toast("已複製觀看網址");});body.addView(copy,lp(-1,dp(52)));LinearLayout controls=row();Button go=button("切換為直播",true);go.setOnClickListener(v->runYouTube("正在檢查 ingest…",()->{if(!youtube.isStreamActive(youtubeSession))throw new IOException("YouTube 尚未收到 RTMP 媒體；請先啟動 RE relay");youtube.transition(youtubeSession,"testing");youtube.transition(youtubeSession,"live");return "live";},x->toast("YouTube Live 已開始")));Button stop=button("結束直播",false);stop.setOnClickListener(v->runYouTube("正在結束直播…",()->{youtube.transition(youtubeSession,"complete");return "complete";},x->toast("直播已結束")));controls.addView(go,new LinearLayout.LayoutParams(0,dp(56),1));controls.addView(stop,new LinearLayout.LayoutParams(0,dp(56),1));body.addView(controls);}TextView relay=text("媒體資料面：YouTube 控制流程已完成；RE 分段媒體 → RTMP relay 尚待實體相機驗證，未就緒前不會啟動公開直播。",14,false);relay.setTextColor(muted);relay.setPadding(0,dp(16),0,dp(24));body.addView(relay);}
    private <T>void runYouTube(String busy,Work<T>w,Done<T>d){status.setText(busy);io.execute(()->{try{T x=w.get();runOnUiThread(()->{try{status.setText("YouTube 就緒");d.ok(x);}catch(Exception e){error(e);}});}catch(Exception e){AppLog.e("YOUTUBE",e.toString());runOnUiThread(()->error(e));}});}
    private void showDevice(){clear("裝置","以易讀欄位查看相機版本、儲存空間與 App 設定。");Button inspect=button("重新讀取裝置資訊",true);inspect.setOnClickListener(v->loadDeviceInfo());body.addView(inspect,lp(-1,dp(56)));loadDeviceInfo();section("介面");Switch theme=toggle("使用深色畫面",dark);theme.setOnCheckedChangeListener((x,on)->{prefs.edit().putBoolean("dark",on).apply();recreate();});body.addView(theme);section("偵錯");Switch debug=toggle("顯示操作 Console",prefs.getBoolean("debug",false));body.addView(debug);debug.setOnCheckedChangeListener((x,on)->{prefs.edit().putBoolean("debug",on).apply();showDevice();});if(debug.isChecked()){console=text(AppLog.export(),12,false);console.setTypeface(Typeface.MONOSPACE);console.setTextIsSelectable(true);console.setPadding(dp(12),dp(12),dp(12),dp(12));console.setBackgroundColor(Color.rgb(16,23,19));console.setTextColor(Color.rgb(200,247,216));body.addView(console,lp(-1,dp(240)));LinearLayout actions=row();Button export=button("匯出 Log",false);export.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("text/plain").putExtra(Intent.EXTRA_TITLE,"re-lens-log.txt").addCategory(Intent.CATEGORY_OPENABLE),EXPORT_LOG));Button clear=button("清除",false);clear.setOnClickListener(v->AppLog.clear());actions.addView(export,new LinearLayout.LayoutParams(0,dp(56),1));actions.addView(clear,new LinearLayout.LayoutParams(0,dp(56),1));body.addView(actions);}TextView app=text("RE Lens "+BuildConfig.VERSION_NAME+"\nBLE 控制 · Wi‑Fi Direct · GC1 媒體",14,false);app.setTextColor(muted);app.setPadding(0,dp(24),0,dp(8));body.addView(app);}
    private void loadDeviceInfo(){final int generation=pageGeneration;status.setText("正在讀取裝置資訊…");io.execute(()->{try{JSONObject info=api().cameraInfo(),storage=api().storage();runOnUiThread(()->{if(generation!=pageGeneration)return;status.setText("裝置資訊已更新");MaterialCardView c=card();LinearLayout box=cardBody(c);box.addView(text("HTC RE",18,true));infoRow(box,"韌體版本",info.optString("firmware_version","未提供"));infoRow(box,"Bootcode 版本",info.optString("bootcode_version","未提供"));infoRow(box,"MCU 版本",info.optString("mcu_version","未提供"));infoRow(box,"協議版本",info.optString("protocol_version","未提供"));long free=storage.optLong("free_bytes",-1),total=storage.optLong("total_bytes",-1);infoRow(box,"可用空間",free>=0?formatBytes(free):"未提供");infoRow(box,"總容量",total>=0?formatBytes(total):"未提供");if(free>=0&&total>0){ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);bar.setProgress((int)((total-free)*1000/total));bar.setContentDescription("儲存空間已使用 "+((total-free)*100/total)+"%");box.addView(bar,lp(-1,dp(20)));}body.addView(c,1,lp(-1,-2));});}catch(Exception e){AppLog.e("DEVICE",e);runOnUiThread(()->{if(generation==pageGeneration){status.setText("無法讀取裝置資訊");toast(e.getMessage());}});}});}
    private void infoRow(LinearLayout parent,String label,String value){LinearLayout row=row();row.setPadding(0,dp(5),0,dp(5));TextView l=text(label,14,false);l.setTextColor(muted);TextView v=text(value,14,true);v.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);row.addView(l,new LinearLayout.LayoutParams(0,dp(38),1));row.addView(v,new LinearLayout.LayoutParams(0,dp(38),1));parent.addView(row);}
    private void confirmDelete(JSONObject item,String name){new AlertDialog.Builder(this).setTitle("從 RE 刪除？").setMessage(name+"\n\n刪除後無法復原；若需要保留，請先下載到手機。").setNegativeButton("取消",null).setPositiveButton("刪除",(d,w)->run("正在刪除…",()->{api().deleteMedia(item);return item;},x->{toast("已從 RE 刪除");showAlbum();})).show();}
    private static String mediaLabel(String type){if("photo".equals(type))return "照片";if(type.contains("video"))return "影片";if("timelapse".equals(type))return "縮時攝影";if("slow_motion".equals(type))return "慢動作影片";return "媒體";}
    private static String formatBytes(long bytes){if(bytes<0)return "未提供";double value=bytes;String[] units={"B","KB","MB","GB","TB"};int unit=0;while(value>=1024&&unit<units.length-1){value/=1024;unit++;}return (unit==0?String.valueOf((long)value):String.format(java.util.Locale.TAIWAN,"%.1f",value))+" "+units[unit];}
    private ReApi api(){String h=host.getText().toString().trim();if(api==null||!api.baseUrl().contains(h)){if(api!=null)api.close();api=new ReApi(h);}return api;}private interface Work<T>{T get()throws Exception;}private interface Done<T>{void ok(T x)throws Exception;}private <T>void run(String busy,Work<T>w,Done<T>d){final int generation=pageGeneration;status.setText(busy);connection.setHttpState("GC1 請求中");io.execute(()->{try{T x=w.get();connection.setHttpState("GC1 可用");runOnUiThread(()->{if(generation!=pageGeneration)return;try{status.setText("GC1 控制已連線");d.ok(x);}catch(Exception e){error(e);}});}catch(Exception e){connection.setHttpState("GC1 失敗");AppLog.e("GC1",e.toString());runOnUiThread(()->{if(generation==pageGeneration)error(e);});}});}
    private void clear(String title,String subtitle){pageGeneration++;stopPreview();body.removeAllViews();statusPanel=null;console=null;body.addView(text(title,28,true));TextView sub=text(subtitle,15,false);sub.setTextColor(muted);sub.setPadding(0,dp(8),0,dp(24));body.addView(sub);}private void section(String s){TextView v=text(s,17,true);v.setPadding(0,dp(28),0,dp(10));body.addView(v);}private EditText passwordField(String hint){EditText x=new EditText(this);x.setSingleLine();x.setHint(hint);x.setTextColor(ink);x.setHintTextColor(muted);x.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);x.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(15)});x.setContentDescription(hint);return x;}private Switch toggle(String s,boolean on){Switch x=new Switch(this);x.setText(s);x.setTextColor(ink);x.setTextSize(16);x.setGravity(Gravity.CENTER_VERTICAL);x.setChecked(on);x.setMinHeight(dp(56));return x;}private MaterialCardView card(){MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(surface);c.setStrokeColor(dark?Color.rgb(63,73,68):Color.rgb(192,201,196));c.setStrokeWidth(dp(1));c.setRadius(dp(16));LinearLayout.LayoutParams p=lp(-1,-2);p.setMargins(0,0,0,dp(12));c.setLayoutParams(p);return c;}private LinearLayout cardBody(MaterialCardView c){LinearLayout box=column();box.setPadding(dp(18),dp(16),dp(18),dp(16));c.addView(box);return box;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=column();l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private TextView text(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(ink);v.setGravity(Gravity.CENTER_VERTICAL);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private Button button(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setMinHeight(dp(48));b.setTextColor(primary?(dark?Color.BLACK:Color.WHITE):ink);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(primary?signal:surface));return b;}private LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private void error(Exception e){status.setText("操作失敗");toast(e.getMessage()==null?e.toString():e.getMessage());}
    @Override public void onStatus(String s){runOnUiThread(()->{if(status!=null)status.setText(s);String ip=connection==null?null:connection.cameraIp();if(ip!=null&&host!=null&&!ip.equals(host.getText().toString().trim())){host.setText(ip);if(api!=null)api.close();api=null;}});}@Override public void onFound(String n,String a){runOnUiThread(()->toast("找到 "+n+" · "+a));}@Override public void onLogChanged(){if(console!=null)runOnUiThread(()->console.setText(AppLog.export()));}
    private void requestPermissionsIfNeeded(){java.util.ArrayList<String> p=new java.util.ArrayList<>();p.add(Manifest.permission.ACCESS_COARSE_LOCATION);p.add(Manifest.permission.ACCESS_FINE_LOCATION);if(Build.VERSION.SDK_INT>=31){p.add(Manifest.permission.BLUETOOTH_SCAN);p.add(Manifest.permission.BLUETOOTH_CONNECT);}if(Build.VERSION.SDK_INT>=33)p.add(Manifest.permission.POST_NOTIFICATIONS);if(Build.VERSION.SDK_INT<=28)p.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);requestPermissions(p.toArray(new String[0]),7);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==YouTubeAuthManager.REQUEST_AUTH&&c==RESULT_OK&&data!=null){youtubeAuth.onActivityResult(data);return;}if(r==EXPORT_LOG&&c==RESULT_OK&&data!=null){Uri u=data.getData();try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(AppLog.export().getBytes(StandardCharsets.UTF_8));toast("Log 已匯出");}catch(Exception e){error(e);}}}
    @Override protected void onDestroy(){pageGeneration++;if(api!=null){api.close();api=null;}connection.removeListener(this);AppLog.removeListener(this);io.shutdownNow();super.onDestroy();}
}
