package tw.xiaoxin.relens;

import org.json.JSONArray;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.time.Instant;

final class YouTubeLiveClient {
    static final class Session {final String broadcastId,streamId,ingestionAddress,streamName,watchUrl;Session(String b,String s,String a,String n){broadcastId=b;streamId=s;ingestionAddress=a;streamName=n;watchUrl="https://www.youtube.com/watch?v="+b;}String maskedIngest(){return ingestionAddress+"/••••••••";}}
    private final String token;YouTubeLiveClient(String token){this.token=token;}
    Session createSession(String title,String privacy)throws Exception{
        JSONObject broadcast=new JSONObject().put("snippet",new JSONObject().put("title",title).put("scheduledStartTime",Instant.now().toString())).put("status",new JSONObject().put("privacyStatus",privacy).put("selfDeclaredMadeForKids",false)).put("contentDetails",new JSONObject().put("enableAutoStart",false).put("enableAutoStop",false));
        JSONObject b=request("POST","/liveBroadcasts?part=snippet,status,contentDetails",broadcast);String broadcastId=required(b,"id");
        JSONObject stream=new JSONObject().put("snippet",new JSONObject().put("title",title)).put("cdn",new JSONObject().put("ingestionType","rtmp").put("resolution","720p").put("frameRate","30fps"));
        JSONObject s=request("POST","/liveStreams?part=snippet,cdn",stream);String streamId=required(s,"id");JSONObject ingest=s.getJSONObject("cdn").getJSONObject("ingestionInfo");String address=required(ingest,"ingestionAddress"),name=required(ingest,"streamName");
        request("POST","/liveBroadcasts/bind?id="+enc(broadcastId)+"&part=id,contentDetails&streamId="+enc(streamId),null);AppLog.i("YOUTUBE","Broadcast and stream created and bound");return new Session(broadcastId,streamId,address,name);
    }
    void transition(Session s,String state)throws Exception{request("POST","/liveBroadcasts/transition?broadcastStatus="+enc(state)+"&id="+enc(s.broadcastId)+"&part=id,status",null);AppLog.i("YOUTUBE","Broadcast transitioned to "+state);}
    boolean isStreamActive(Session s)throws Exception{JSONObject response=request("GET","/liveStreams?part=status&id="+enc(s.streamId),null);JSONArray items=response.optJSONArray("items");if(items==null||items.length()==0)return false;JSONObject status=items.getJSONObject(0).optJSONObject("status");return status!=null&&"active".equals(status.optString("streamStatus"));}
    private JSONObject request(String method,String path,JSONObject body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("https://www.googleapis.com/youtube/v3"+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(10000);c.setReadTimeout(20000);c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Accept","application/json");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream raw=code>=400?c.getErrorStream():c.getInputStream();String text=read(raw);c.disconnect();if(code<200||code>=300)throw new IOException("YouTube API HTTP "+code+publicError(text));return text.isEmpty()?new JSONObject():new JSONObject(text);}
    private static String required(JSONObject o,String key)throws Exception{String v=o.optString(key,"");if(v.isEmpty())throw new IOException("YouTube response missing "+key);return v;}private static String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}private static String read(InputStream in)throws Exception{if(in==null)return "";try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder b=new StringBuilder();String s;while((s=r.readLine())!=null)b.append(s);return b.toString();}}private static String publicError(String json){try{return ": "+new JSONObject(json).getJSONObject("error").optString("message","request failed");}catch(Exception ignored){return ": request failed";}}
}
